import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import { Footer } from "@/components/ui/footer";
import { Header } from "@/components/ui/header";
import { Providers } from "@/components/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
        <main className="flex-1">
          {children}
        </main>
          <Footer 
          logo={<Image src="/next.svg" alt="Next.js Logo" width={24} height={24} className="dark:invert" />}
          brandName="Next.js"
          socialLinks={[
            {
              icon: <Image src="/vercel.svg" alt="Vercel" width={20} height={20} className="dark:invert" />,
              href: "https://vercel.com",
              label: "Vercel"
            }
          ]}
          mainLinks={[
            {
              href: "https://nextjs.org/docs",
              label: "Documentation"
            },
            {
              href: "https://nextjs.org/learn",
              label: "Learn"
            },
            {
              href: "https://vercel.com/templates",
              label: "Templates"
            }
          ]}
          legalLinks={[
            {
              href: "https://vercel.com/terms",
              label: "Terms"
            },
            {
              href: "https://vercel.com/privacy",
              label: "Privacy Policy"
            }
          ]}
          copyright={{
            text: "© 2024 Vercel, Inc. All rights reserved.",
            license: "Released under the MIT License"
          }}
          />
        </Providers>
      </body>
    </html>
  );
}
