# Configuration file for AiderAgent
prompt: "ai_docs/code_gen_tools/test_writing_prompt.md"
coder_model: "ollama/deepseek-r1:70b"
evaluator_model: "ollama/deepseek-r1:70b"
max_iterations: 3
execution_commands:
  - command: "npm test"
    description: "Run tests"
  - command: "vercel build"
    description: "Verify build"
context_editable:
  - "components/ui/**/*.tsx"
  - "components/ui/**/*.ts" 
  - "__tests__/**/*.test.tsx"
  - "__tests__/**/*.test.ts"
context_read_only:
  - "ai_docs/DEVELOPER_GUIDELINES.md"
evaluator: "default"
program_type: "script"
startup_timeout: 5
health_check_command: null
