name: Update Database Types

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  # Optionally run manually from GitHub UI
  workflow_dispatch:

jobs:
  update-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Required for creating PR/pushing changes
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Generate Types
        run: |
          supabase gen types typescript --project-id ${{ secrets.SUPABASE_PROJECT_ID }} > types/database.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Optional: Create PR if types changed
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update database types'
          title: 'chore: update database types'
          body: 'Auto-generated database types from Supabase schema'
          branch: update-db-types
          delete-branch: true
